### ISSUE TITLE
Add support for alpaca

### ISSUE THREAD

**Issue by maxscheel** [avilum/llama-saas#1]
How hard would it be to add support for the alpaca model (usage below)
[https://github.com/ggerganov/llama.cpp/blob/master/alpaca.sh
](https://github.com/ggerganov/llama.cpp/blob/master/alpaca.sh
)

**Comment by avilum** [comment]
Very easy - just replace the Cmd command in `server.go`.

https://github.com/avilum/llama-saas/blob/master/server.go#L21

It should be as simple as that.
Let me know if you managed to run it 🙏🏻
